package com.ianblk.zianmanager.core;
import java.nio.file.Path;
import java.io.IOException;
import java.time.*;
import java.util.*;
/** Daily shared allowance across selected worlds; never stores a reconnectable session clock. */
public final class DailyDungeonTime {
 public record Pulse(Instant at,long seconds){}
 public static Pulse pulse(Instant previous,Instant now,LocalDate day,ZoneId zone){if(previous==null)return new Pulse(now,1);Instant base=previous.atZone(zone).toLocalDate().equals(day)?previous:day.atStartOfDay(zone).toInstant();long seconds=Math.max(0,Duration.between(base,now).getSeconds());return new Pulse(base.plusSeconds(seconds),seconds);}
 public record Tier(String name,String permission,int weekday,int weekend){public Tier{if(name==null || name.isBlank() || name.length()>64 || !permission.matches("[a-z0-9_.-]{1,128}") || weekday<1 || weekday>1440 || weekend<1 || weekend>1440)throw new IllegalArgumentException("Rango: nombre, permiso y minutos entre 1 y 1440");}public long limit(LocalDate day){return 60L*(day.getDayOfWeek()==DayOfWeek.SATURDAY || day.getDayOfWeek()==DayOfWeek.SUNDAY?weekend:weekday);}}
 public record Settings(boolean enabled,List<String> worlds,String timezone,int defaultWeekday,int defaultWeekend,int vipWeekday,int vipWeekend,String vipPermission,String bypassPermission,String exitCommand,List<Tier> tiers,String resetMessage,String exhaustedMessage,Integer hudX,Integer hudY,Boolean hudEnabled){
  public Settings(boolean enabled,List<String> worlds,String timezone,int defaultWeekday,int defaultWeekend,int vipWeekday,int vipWeekend,String vipPermission,String bypassPermission,String exitCommand,List<Tier> tiers,String resetMessage,String exhaustedMessage){this(enabled,worlds,timezone,defaultWeekday,defaultWeekend,vipWeekday,vipWeekend,vipPermission,bypassPermission,exitCommand,tiers,resetMessage,exhaustedMessage,2,12,true);}
  public Settings(boolean enabled,List<String> worlds,String timezone,int defaultWeekday,int defaultWeekend,int vipWeekday,int vipWeekend,String vipPermission,String bypassPermission,String exitCommand,List<Tier> tiers){this(enabled,worlds,timezone,defaultWeekday,defaultWeekend,vipWeekday,vipWeekend,vipPermission,bypassPermission,exitCommand,tiers,"¡El tiempo diario de las dungeons se ha regenerado!","Se te acabó el tiempo por el día de hoy. Tu tiempo se renovará a las 00:00 UTC -5.");}
  public Settings(boolean enabled,List<String> worlds,String timezone,int defaultWeekday,int defaultWeekend,int vipWeekday,int vipWeekend,String vipPermission,String bypassPermission,String exitCommand){this(enabled,worlds,timezone,defaultWeekday,defaultWeekend,vipWeekday,vipWeekend,vipPermission,bypassPermission,exitCommand,List.of());}
  public Settings{hudX=hudX==null?2:hudX;hudY=hudY==null?12:hudY;hudEnabled=hudEnabled==null?true:hudEnabled;if(hudX<0 || hudX>100 || hudY<0 || hudY>100)throw new IllegalArgumentException("Posición del temporizador: 0–100%");resetMessage=resetMessage==null?"¡El tiempo diario de las dungeons se ha regenerado!":resetMessage;exhaustedMessage=exhaustedMessage==null?"Se te acabó el tiempo por el día de hoy. Tu tiempo se renovará a las 00:00 UTC -5.":exhaustedMessage;if(resetMessage.isBlank() || exhaustedMessage.isBlank() || resetMessage.length()>512 || exhaustedMessage.length()>512)throw new IllegalArgumentException("Mensajes: 1–512 caracteres");tiers=List.copyOf(tiers==null?List.of():tiers);if(tiers.size()>16 || tiers.stream().map(Tier::permission).distinct().count()!=tiers.size())throw new IllegalArgumentException("Hasta 16 rangos con permisos distintos");worlds=List.copyOf(worlds);ZoneId.of(timezone);if(worlds.size()>64 || worlds.stream().anyMatch(w->w.isBlank() || w.length()>128) || enabled && worlds.isEmpty())throw new IllegalArgumentException("Selecciona al menos un mundo de dungeon");for(int value:List.of(defaultWeekday,defaultWeekend,vipWeekday,vipWeekend))if(value<1 || value>1440)throw new IllegalArgumentException("Límite: 1–1440 minutos");if(!vipPermission.matches("[a-z0-9_.-]{1,128}") || !bypassPermission.matches("[a-z0-9_.-]{1,128}") || exitCommand.isBlank() || exitCommand.length()>2048 || exitCommand.chars().anyMatch(Character::isISOControl) || !exitCommand.contains("{player}"))throw new IllegalArgumentException("Permisos o comando de salida inválidos; usa {player}");}
  public static Settings defaults(){return new Settings(false,List.of(),"America/Guayaquil",30,90,120,180,"zianmanager.dungeon.vip","zianmanager.dungeon.bypass","spawn {player}");}
  public LocalDate day(Instant instant){return instant.atZone(ZoneId.of(timezone)).toLocalDate();}
  public long limit(Instant instant,boolean vip){var weekday=day(instant).getDayOfWeek();boolean weekend=weekday==DayOfWeek.SATURDAY || weekday==DayOfWeek.SUNDAY;return 60L*(vip?(weekend?vipWeekend:vipWeekday):(weekend?defaultWeekend:defaultWeekday));}
 }
 public record Usage(String day,long seconds,long bonusSeconds){public Usage(String day,long seconds){this(day,seconds,0);}public Usage{if(bonusSeconds<0 || bonusSeconds>86400)throw new IllegalArgumentException("Bono máximo diario: 24 horas");LocalDate.parse(day);if(seconds<0 || seconds>172800)throw new IllegalArgumentException("Uso diario inválido");}}
 public record GlobalBonus(String day,long seconds){public GlobalBonus{LocalDate.parse(day);if(seconds<0 || seconds>86400)throw new IllegalArgumentException("Bono global máximo: 24 horas");}}
 private record Data(int schema,Map<UUID,Usage> users,GlobalBonus global,String announcedDay){Data{announcedDay=announcedDay==null?"":announcedDay;if(!announcedDay.isEmpty())LocalDate.parse(announcedDay);global=global==null?new GlobalBonus("1970-01-01",0):global;if(schema!=1 || users.size()>100000)throw new IllegalArgumentException("Registro de tiempo inválido");users=Map.copyOf(users);}}
 private final Path file;private Map<UUID,Usage> users;private GlobalBonus global;private String announcedDay;
 public DailyDungeonTime(Path file)throws IOException{this.file=file;var data=AtomicJson.read(file,Data.class,new Data(1,Map.of(),null,""));users=data.users();global=data.global();announcedDay=data.announcedDay();}
 public long used(UUID player,LocalDate day){var usage=users.get(player);return usage!=null && usage.day().equals(day.toString())?usage.seconds():0;}
 public void charge(Map<UUID,Long> seconds,LocalDate day)throws IOException{if(seconds.isEmpty())return;var next=new HashMap<>(users);for(var entry:seconds.entrySet()){long amount=entry.getValue();if(amount==0)continue;if(amount<0)throw new IllegalArgumentException("Tiempo negativo");next.put(entry.getKey(),new Usage(day.toString(),Math.min(172800,used(entry.getKey(),day)+amount),personalBonus(entry.getKey(),day)));}if(!next.equals(users))AtomicJson.write(file,new Data(1,next,global,announcedDay));users=Map.copyOf(next);}
 public long personalBonus(UUID player,LocalDate day){var row=users.get(player);return row!=null && row.day().equals(day.toString())?row.bonusSeconds():0;}
 public long bonus(UUID player,LocalDate day){return personalBonus(player,day)+(global.day().equals(day.toString())?global.seconds():0);}
 public void grant(UUID player,LocalDate day,long seconds)throws IOException{if(seconds<1 || seconds>86400)throw new IllegalArgumentException("Bono: 1 segundo a 24 horas");var next=new HashMap<>(users);var newGlobal=global;if(player==null)newGlobal=new GlobalBonus(day.toString(),(global.day().equals(day.toString())?global.seconds():0)+seconds);else next.put(player,new Usage(day.toString(),used(player,day),personalBonus(player,day)+seconds));AtomicJson.write(file,new Data(1,next,newGlobal,announcedDay));users=Map.copyOf(next);global=newGlobal;}
 public boolean announceDue(Instant now,Settings settings){var local=now.atZone(ZoneId.of(settings.timezone()));return local.getHour()==0 && local.getMinute()>=1 && !announcedDay.equals(local.toLocalDate().toString());}
 public void markAnnouncement(LocalDate day)throws IOException{AtomicJson.write(file,new Data(1,users,global,day.toString()));announcedDay=day.toString();}
 public long remaining(UUID player,Instant now,Settings settings,boolean vip){return Math.max(0,settings.limit(now,vip)+bonus(player,settings.day(now))-used(player,settings.day(now)));}
}
