package com.ianblk.zianmanager.reward;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.junit.jupiter.api.Assertions.*;
class LootDeliveryTest {
    @TempDir Path dir;
    private RewardDefinition reward(int count,boolean repeat){var items=new ArrayList<String>();for(int i=0;i<count;i++)items.add("frozen-item-"+i);return new RewardDefinition("",0,items,repeat?RewardDefinition.Mode.REPEAT:RewardDefinition.Mode.UNIQUE,repeat?1:0);}
    private RewardDelivery.Port port(AtomicInteger delivered){return new RewardDelivery.Port(){public String unavailable(RewardClaim.Part p){return null;}public RewardDelivery.Result apply(RewardClaim.Part p){delivered.incrementAndGet();return RewardDelivery.Result.APPLIED;}};}
    @Test void chestCanDeliverTenPartsAndNeverReplays() throws Exception{var journal=RewardJournal.open(dir.resolve("claims.json"));var player=UUID.randomUUID();journal.reserveAt(player,"chest.test",reward(10,true),1000,UUID.randomUUID());var id=journal.latest(player,"chest.test").id();var calls=new AtomicInteger();RewardDelivery.deliver(journal,player,id,port(calls));RewardDelivery.deliver(RewardJournal.open(dir.resolve("claims.json")),player,id,port(calls));assertEquals(10,calls.get());}
    @Test void cooldownStartsAfterConfirmedDeliveryNotWhenPreviewWasOpened() throws Exception{var journal=RewardJournal.open(dir.resolve("claims.json"));var player=UUID.randomUUID();journal.reserveAt(player,"chest.test",reward(1,true),1000,UUID.randomUUID());var id=journal.latest(player,"chest.test").id();assertEquals(-2,journal.remaining(player,"chest.test",reward(1,true),System.currentTimeMillis()));RewardDelivery.deliver(journal,player,id,port(new AtomicInteger()));assertTrue(journal.remaining(player,"chest.test",reward(1,true),System.currentTimeMillis())>59000);}
    @Test void interruptedIntentIsHeldForReviewAfterRestart() throws Exception{var path=dir.resolve("claims.json");var journal=RewardJournal.open(path);var player=UUID.randomUUID();journal.reserve(player,"mob.test",reward(1,false));var id=journal.latest(player,"mob.test").id();journal.phase(id,0,RewardClaim.Phase.APPLYING,"started");var calls=new AtomicInteger();RewardDelivery.deliver(RewardJournal.open(path),player,id,port(calls));assertEquals(0,calls.get());}
    @Test void anotherPlayerCannotClaimPersonalLoot() throws Exception{var journal=RewardJournal.open(dir.resolve("claims.json"));var owner=UUID.randomUUID();journal.reserve(owner,"chest.test",reward(1,false));var id=journal.latest(owner,"chest.test").id();assertThrows(IllegalArgumentException.class,()->RewardDelivery.deliver(journal,UUID.randomUUID(),id,port(new AtomicInteger())));}
    @Test void fullInventoryDoesNotConsumeOrRerollReward() throws Exception{var journal=RewardJournal.open(dir.resolve("claims.json"));var player=UUID.randomUUID();journal.reserve(player,"mob.test",reward(2,false));var before=journal.latest(player,"mob.test");var calls=new AtomicInteger();RewardDelivery.deliver(journal,player,before.id(),new RewardDelivery.Port(){public String unavailable(RewardClaim.Part p){return "full";}public RewardDelivery.Result apply(RewardClaim.Part p){calls.incrementAndGet();return RewardDelivery.Result.APPLIED;}});assertEquals(0,calls.get());assertEquals(before.parts().stream().map(RewardClaim.Part::data).toList(),journal.latest(player,"mob.test").parts().stream().map(RewardClaim.Part::data).toList());}
    @Test void independentChestKeysHaveIndependentCooldowns() throws Exception{var journal=RewardJournal.open(dir.resolve("claims.json"));var player=UUID.randomUUID();assertTrue(journal.reserveAt(player,"chest.first",reward(1,true),1000,UUID.randomUUID()));assertTrue(journal.reserveAt(player,"chest.second",reward(1,true),1000,UUID.randomUUID()));}
    @Test void corruptJournalPreservesSource() throws Exception{var file=dir.resolve("claims.json");Files.writeString(file,"broken");assertThrows(java.io.IOException.class,()->RewardJournal.open(file));assertEquals("broken",Files.readString(file));}
    @Test void invalidLootSizesFailBeforeMutation(){assertThrows(IllegalArgumentException.class,()->reward(33,true));assertDoesNotThrow(()->reward(32,true));}
}
