package lat.rassvet.rules;
import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.player.*;
import org.bukkit.event.inventory.*;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.potion.*;
import java.io.File;
import java.util.regex.Pattern;
import org.bukkit.inventory.*;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.java.JavaPlugin;
import java.util.*;

/** Small server companion: preserve EternalCore permissions and death tracking. */
public final class RassvetRules extends JavaPlugin implements Listener,CommandExecutor,TabCompleter {
 private NamespacedKey flight;private String lobby;private double minimumY;private Location spawn;private long spawnStamp=-1;private final Map<UUID,Long> rescue=new HashMap<>(),backPending=new HashMap<>();private final Map<UUID,String> commandStates=new HashMap<>();private boolean auditing;
 private static final Pattern POSITION=Pattern.compile("Position\\{x=([-0-9.]+), y=([-0-9.]+), z=([-0-9.]+), yaw=([-0-9.]+), pitch=([-0-9.]+), world='([^']+)'\\}");
 private static final class TpaMenu implements InventoryHolder {
  private Inventory inventory;private final Map<Integer,UUID> targets=new HashMap<>();
  public Inventory getInventory(){return inventory;}
 }
 @Override public void onEnable(){saveDefaultConfig();lobby=getConfig().getString("lobby-world","world");minimumY=getConfig().getDouble("void-min-y",0);flight=new NamespacedKey(this,"lobby_flight");getServer().getPluginManager().registerEvents(this,this);getCommand("rassvet").setExecutor(this);getCommand("rassvet").setTabCompleter(this);getServer().getOnlinePlayers().forEach(this::checkFlight);refreshSpawn();getServer().getScheduler().runTaskTimer(this,()->{refreshSpawn();backPending.entrySet().removeIf(e->e.getValue()<System.currentTimeMillis());for(Player p:getServer().getOnlinePlayers()){if(lobbyPlayer(p) && p.getLocation().getY()<minimumY)rescue(p);String state=p.isOp()+"/"+p.getWorld().getName()+"/"+p.hasPermission("commandwhitelist.bypass")+"/"+p.hasPermission("commandwhitelist.group.explorador")+"/"+p.hasPermission("commandwhitelist.group.guardian")+"/"+p.hasPermission("commandwhitelist.group.astral");if(!state.equals(commandStates.put(p.getUniqueId(),state)))p.updateCommands();}},20,20);getLogger().info("Death-only /back, 10s Resistance II, TPA menu, void rescue and lobby flight guard enabled");}
 private boolean lobbyPlayer(Player p){return p.getWorld().getName().equals(lobby) && p.getGameMode()!=GameMode.CREATIVE && p.getGameMode()!=GameMode.SPECTATOR;}
 private void refreshSpawn(){File file=new File(getDataFolder().getParentFile(),"EternalCore/locations.yml");if(file.lastModified()==spawnStamp)return;spawnStamp=file.lastModified();String value=YamlConfiguration.loadConfiguration(file).getString("spawn","");var match=POSITION.matcher(value);if(match.matches()){World world=Bukkit.getWorld(match.group(6));if(world!=null && world.getName().equals(lobby))spawn=new Location(world,Double.parseDouble(match.group(1)),Double.parseDouble(match.group(2)),Double.parseDouble(match.group(3)),Float.parseFloat(match.group(4)),Float.parseFloat(match.group(5)));}if(spawn==null){World world=Bukkit.getWorld(lobby);if(world!=null)spawn=world.getSpawnLocation();}}
 private void rescue(Player p){long now=System.currentTimeMillis();if(now<rescue.getOrDefault(p.getUniqueId(),0L) || spawn==null)return;rescue.put(p.getUniqueId(),now+2000);p.setFallDistance(0);if(p.teleport(spawn,PlayerTeleportEvent.TeleportCause.PLUGIN)){p.setFallDistance(0);p.sendMessage("§eTe devolvimos al Spawn para evitar el vacío.");}}
 private void requestBack(Player p){if(!p.hasPermission("eternalcore.back") || !p.hasPermission("eternalcore.back.death")){p.sendMessage("§cNo tienes permiso para volver a tu muerte.");return;}if(backPending.containsKey(p.getUniqueId())){p.sendMessage("§eYa tienes un regreso pendiente.");return;}Location death=p.getLastDeathLocation();if(death==null || death.getWorld()==null){p.sendMessage("§cNo hay una última muerte registrada.");return;}if(death.getY()<death.getWorld().getMinHeight() || death.getY()>=death.getWorld().getMaxHeight()){p.sendMessage("§cLa última muerte está fuera de los límites del mundo.");return;}Location destination=death.clone().add(0.5,0.1,0.5),start=p.getLocation();int wait=Math.max(0,Math.min(60,getConfig().getInt("back-wait-seconds",5)));long token=System.currentTimeMillis()+wait*1000L+2000;backPending.put(p.getUniqueId(),token);p.sendMessage("§eRegresarás a tu última muerte en "+wait+" segundos. No te muevas.");getServer().getScheduler().runTaskLater(this,()->{if(!Objects.equals(backPending.get(p.getUniqueId()),token))return;backPending.remove(p.getUniqueId());if(!p.isOnline() || !p.hasPermission("eternalcore.back.death") || !p.hasPermission("eternalcore.back"))return;if(!p.getWorld().equals(start.getWorld()) || p.getLocation().distanceSquared(start)>0.0625){p.sendMessage("§cRegreso cancelado porque te moviste.");return;}if(p.teleport(destination,PlayerTeleportEvent.TeleportCause.PLUGIN)){p.setFallDistance(0);getServer().getScheduler().runTask(this,()->{if(p.isOnline() && p.getWorld().equals(destination.getWorld()) && p.getLocation().distanceSquared(destination)<=64){p.addPotionEffect(new PotionEffect(PotionEffectType.RESISTANCE,200,1,false,true,true));p.sendMessage("§aRegresaste a tu última muerte. Resistencia II durante 10 segundos.");}});}else p.sendMessage("§cNo se pudo regresar a tu última muerte.");},wait*20L);}
 @EventHandler(ignoreCancelled=true) public void move(PlayerMoveEvent e){if(e.getTo()!=null && lobbyPlayer(e.getPlayer()) && e.getTo().getY()<minimumY)rescue(e.getPlayer());}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void damage(EntityDamageEvent e){if(!(e.getEntity() instanceof Player p))return;if(backPending.remove(p.getUniqueId())!=null)p.sendMessage("§cRegreso cancelado porque recibiste daño.");if(lobbyPlayer(p) && e.getCause()==EntityDamageEvent.DamageCause.VOID){e.setCancelled(true);rescue(p);}}
 @EventHandler public void quit(PlayerQuitEvent e){rescue.remove(e.getPlayer().getUniqueId());backPending.remove(e.getPlayer().getUniqueId());commandStates.remove(e.getPlayer().getUniqueId());}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true) public void backTeleport(PlayerTeleportEvent e){Player p=e.getPlayer();Long until=backPending.get(p.getUniqueId());Location death=p.getLastDeathLocation();if(until==null || until<System.currentTimeMillis() || death==null || e.getTo()==null || !death.getWorld().equals(e.getTo().getWorld()) || death.distanceSquared(e.getTo())>64)return;backPending.remove(p.getUniqueId());Location destination=e.getTo().clone();getServer().getScheduler().runTask(this,()->{if(p.isOnline() && p.getWorld().equals(destination.getWorld()) && p.getLocation().distanceSquared(destination)<=64)p.addPotionEffect(new PotionEffect(PotionEffectType.RESISTANCE,200,1,false,true,true));});}
 private boolean owned(Player p){return p.getPersistentDataContainer().has(flight,PersistentDataType.BYTE);}
 private boolean exempt(Player p){return p.isOp() || p.hasPermission("rassvet.flight.bypass") || p.getGameMode()==GameMode.CREATIVE || p.getGameMode()==GameMode.SPECTATOR;}
 private void checkFlight(Player p){if(!owned(p) || exempt(p) || p.getWorld().getName().equals(lobby))return;p.setFlying(false);p.setAllowFlight(false);p.getPersistentDataContainer().remove(flight);p.sendMessage("§eEl vuelo de tu rango solo está disponible en Spawn.");}
 private void markFlight(Player p){getServer().getScheduler().runTask(this,()->{if(!p.isOnline())return;if(p.getAllowFlight() && p.getWorld().getName().equals(lobby))p.getPersistentDataContainer().set(flight,PersistentDataType.BYTE,(byte)1);else p.getPersistentDataContainer().remove(flight);checkFlight(p);});}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void command(PlayerCommandPreprocessEvent e){if(auditing)return;String[] words=e.getMessage().substring(1).trim().split("\\s+");String root=words[0].toLowerCase(Locale.ROOT);String bare=root.substring(root.lastIndexOf(':')+1);Player p=e.getPlayer();if(bare.equals("back") && (words.length==1 || words.length==2 && words[1].equalsIgnoreCase("death")) && p.hasPermission("eternalcore.back") && p.hasPermission("eternalcore.back.death")){e.setCancelled(true);requestBack(p);return;}if(bare.equals("fly") && !exempt(p) && p.hasPermission("rassvet.lobbyflight")){if(!p.getWorld().getName().equals(lobby)){e.setCancelled(true);p.sendMessage("§eEl vuelo de tu rango solo está disponible en Spawn.");}else markFlight(p);}}
 @EventHandler public void changedWorld(PlayerChangedWorldEvent e){checkFlight(e.getPlayer());getServer().getScheduler().runTask(this,e.getPlayer()::updateCommands);}
 @EventHandler public void join(PlayerJoinEvent e){getServer().getScheduler().runTask(this,()->checkFlight(e.getPlayer()));}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void flight(PlayerToggleFlightEvent e){if(owned(e.getPlayer()) && !exempt(e.getPlayer()) && !e.getPlayer().getWorld().getName().equals(lobby)){e.setCancelled(true);checkFlight(e.getPlayer());}}
 private void tpa(Player p){var holder=new TpaMenu();holder.inventory=Bukkit.createInventory(holder,54,"Solicitar teletransporte");int slot=0;for(Player target:getServer().getOnlinePlayers()){if(slot>=54)break;if(target.equals(p) || !p.canSee(target))continue;var item=new ItemStack(Material.ENDER_PEARL);var meta=item.getItemMeta();meta.setDisplayName("§b"+target.getName());meta.setLore(List.of("§7Enviar una solicitud de TPA","§8Requiere que acepte la solicitud"));item.setItemMeta(meta);holder.inventory.setItem(slot,item);holder.targets.put(slot++,target.getUniqueId());}p.openInventory(holder.inventory);}
 @EventHandler(priority=EventPriority.HIGHEST) public void inventoryClick(InventoryClickEvent e){if(!(e.getView().getTopInventory().getHolder() instanceof TpaMenu menu))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p) || e.getRawSlot()<0 || e.getRawSlot()>=54)return;UUID targetId=menu.targets.get(e.getRawSlot());if(targetId==null)return;p.closeInventory();Player target=Bukkit.getPlayer(targetId);if(!p.hasPermission("rassvet.tpa") || !p.hasPermission("eternalcore.tpa") || target==null || !p.canSee(target)){p.sendMessage("§cLa solicitud ya no está disponible.");return;}p.performCommand("tpa "+target.getName());}
 @EventHandler(priority=EventPriority.HIGHEST) public void inventoryDrag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof TpaMenu)e.setCancelled(true);}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){
  String action=args.length==0?"tpa":args[0].toLowerCase(Locale.ROOT);
  if(action.equals("tpa") && sender instanceof Player p){if(!p.hasPermission("rassvet.tpa") || !p.hasPermission("eternalcore.tpa")){p.sendMessage("§cNo tienes permiso para solicitar TPA.");return true;}tpa(p);return true;}
  if(action.equals("regreso") && sender instanceof Player p){requestBack(p);return true;}
  if(action.equals("vuelo") && sender instanceof Player p){if(!p.hasPermission("eternalcore.fly") || !p.hasPermission("rassvet.lobbyflight")){p.sendMessage("§cNo tienes permiso para volar.");return true;}if(!exempt(p) && !p.getWorld().getName().equals(lobby)){p.sendMessage("§eEl vuelo de tu rango solo está disponible en Spawn.");return true;}p.performCommand("fly");markFlight(p);return true;}
  if(!sender.hasPermission("rassvet.admin")){sender.sendMessage("§cComando no disponible.");return true;}
  if(action.equals("refresh")){getServer().getOnlinePlayers().forEach(Player::updateCommands);sender.sendMessage("Árboles de comandos actualizados.");return true;}
  if(action.equals("audit") && args.length==2){Player p=Bukkit.getPlayerExact(args[1]);if(p==null){sender.sendMessage("Jugador desconectado.");return true;}var event=new PlayerCommandSendEvent(p,new TreeSet<>(List.of("plugins","pl","version","ver","about","bukkit:plugins","bukkit:version","lp","mv","ZianGui","ziangui","ZianGTS","ziangts","ZianUtilities","zianutilities","zianmanager","spawn","tpa","fly","back","rassvet","pc","healpokemon","enderchest","workbench","hat")));getServer().getPluginManager().callEvent(event);sender.sendMessage("Rassvet audit "+p.getName()+" op="+p.isOp()+" world="+p.getWorld().getName()+" visible="+String.join(",",event.getCommands()));try{auditing=true;for(String probe:List.of("/plugins","/bukkit:plugins","/lp info","/back")){var attempt=new PlayerCommandPreprocessEvent(p,probe);getServer().getPluginManager().callEvent(attempt);sender.sendMessage("Probe "+probe+" cancelled="+attempt.isCancelled());}}finally{auditing=false;}sender.sendMessage("Permissions: tpa="+p.hasPermission("eternalcore.tpa")+" fly="+p.hasPermission("eternalcore.fly")+" back.death="+p.hasPermission("eternalcore.back.death")+" bypass="+p.hasPermission("commandwhitelist.bypass"));return true;}
  sender.sendMessage("/rassvet audit <jugador> | /rassvet refresh");return true;
 }
 @Override public List<String> onTabComplete(CommandSender sender,Command cmd,String alias,String[] args){if(args.length!=1)return List.of();var choices=new ArrayList<String>();if(sender.hasPermission("rassvet.tpa"))choices.add("tpa");if(sender.hasPermission("eternalcore.back.death"))choices.add("regreso");if(sender.hasPermission("rassvet.lobbyflight") && sender.hasPermission("eternalcore.fly") && (!(sender instanceof Player p) || p.getWorld().getName().equals(lobby) || exempt(p)))choices.add("vuelo");if(sender.hasPermission("rassvet.admin"))choices.addAll(List.of("audit","refresh"));return choices.stream().filter(s->s.startsWith(args[0].toLowerCase(Locale.ROOT))).toList();}
}
