package com.ianblk.zianmanager.client;
import com.google.gson.*;
import com.ianblk.zianmanager.ManagerNetwork;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.network.chat.Component;
import net.neoforged.neoforge.network.PacketDistributor;
import java.util.*;
public final class ManagerScreen extends ManagerThemedScreen {
 private static final Map<String,String> LAST_TAB=new HashMap<>();
 private final JsonObject data;private final String type,id;private final UUID token;
 private final LinkedHashMap<String,String> values=new LinkedHashMap<>();private final Map<String,EditBox> inputs=new LinkedHashMap<>();
 private final Map<String,int[]> labels=new LinkedHashMap<>();private String tab;private int page,left,top,w,h;
 public ManagerScreen(JsonObject data){super(Component.literal(EditorSections.title(data.get("type").getAsString())));this.data=data;type=data.get("type").getAsString();id=data.get("id").getAsString();token=UUID.fromString(data.get("token").getAsString());if(data.has("fields"))data.getAsJsonObject("fields").entrySet().forEach(e->values.put(e.getKey(),e.getValue().getAsString()));tab=LAST_TAB.getOrDefault(type,EditorSections.groups(type).keySet().stream().findFirst().orElse(""));}
 private boolean list(){return type.equals("root") || type.endsWith("s") || type.equals("lootlist") || type.equals("claim");}
 @Override protected void init(){w=Math.min(430,width-24);h=Math.min(294,height-16);left=(width-w)/2;top=(height-h)/2;inputs.clear();labels.clear();
  if(list()){listWidgets();return;}
  var groups=EditorSections.groups(type);if(!groups.containsKey(tab))tab=groups.keySet().iterator().next();int i=0,tw=(w-24)/Math.max(1,groups.size());
  for(String name:groups.keySet()){var b=button(left+12+i++*tw,top+32,tw-3,name,()->{tab=name;LAST_TAB.put(type,tab);page=0;rebuildWidgets();});b.active=!name.equals(tab);}
  List<String> keys=groups.get(tab).stream().filter(values::containsKey).toList();int pages=Math.max(1,(keys.size()+3)/4);page=Math.min(page,pages-1);
  int col=(w-36)/2;
  for(i=page*4;i<Math.min(keys.size(),(page+1)*4);i++){String key=keys.get(i);int index=i-page*4;field(key,left+12+(index%2)*(col+12),top+98+(index/2)*42,col);}
  if(type.equals("npc") && tab.equals("Diálogo")){var box=new MultiLineEditBox(font,left+12,top+98,w-24,Math.max(40,h-172),Component.literal("Escribe lo que dirá el personaje…"),Component.literal("Diálogo"));box.setCharacterLimit(1024);box.setValue(values.getOrDefault("text","").replace("\\n","\n"));box.setValueListener(v->values.put("text",v));addRenderableWidget(box);}
  if(type.equals("mob") && tab.equals("Efectos"))button(left+12,top+98,w-24,"Elegir y configurar efectos",()->minecraft.setScreen(new EffectsScreen(this,values.getOrDefault("effects",""),v->{values.put("effects",v);minecraft.setScreen(this);})));
  if(type.equals("time") && tab.equals("Rangos"))button(left+12,top+98,w-24,"Configurar rangos adicionales",()->minecraft.setScreen(new TimeTiersScreen(this,values.getOrDefault("tiers","[]"),v->{values.put("tiers",v);minecraft.setScreen(this);})));
  var actions=new ArrayList<Runnable>();var names=new ArrayList<String>();
  if(type.equals("zone") && tab.equals("Ubicación")){action(names,actions,"Crear zona de dungeon",()->send("center"));action(names,actions,"Cerrar y ver zona",this::onClose);action(names,actions,"Mostrar / ocultar zona",()->ZonePreview.visible=!ZonePreview.visible);}
  else{action(names,actions,type.equals("zone") && tab.equals("Tamaño")?"Aplicar tamaño":"Guardar cambios",()->send(type.equals("zone") && tab.equals("Tamaño")?"resize":"save"));
   if(type.equals("mob") && tab.equals("Equipo"))action(names,actions,"Copiar objeto de mano",()->send("equip"));
   if(type.equals("mob") && (tab.equals("Básico") || tab.equals("Equipo")))action(names,actions,"Ver mob de prueba",()->send("preview"));
   if(type.equals("loot") && tab.equals("Objetos")){action(names,actions,"Añadir objeto de mano",()->send("add"));action(names,actions,"Editar seleccionado",()->send("edit_entry"));}
   if(type.equals("zone") && tab.equals("Tamaño")){action(names,actions,"Cerrar y ver zona",this::onClose);action(names,actions,"Mostrar / ocultar",()->ZonePreview.visible=!ZonePreview.visible);}
   if(type.equals("time") && tab.equals("Pantalla"))action(names,actions,"Mover temporizador",()->minecraft.setScreen(new TimerPositionScreen(this,percent("hudX",2),percent("hudY",12),(x,y)->{values.put("hudX",""+x);values.put("hudY",""+y);send("save");})));
   if(type.equals("time") && tab.equals("Salida")){action(names,actions,"Cama → spawn",()->{values.put("exitCommand","bed");rebuildWidgets();});action(names,actions,"Spawn del mundo",()->{values.put("exitCommand","worldspawn");rebuildWidgets();});}
   if(type.equals("time") && tab.equals("Mundos"))action(names,actions,"Añadir mundo actual",()->send("add_world"));
   if(type.equals("zone") && !id.isEmpty())action(names,actions,"Aplicar y reiniciar",()->send("apply_zone"));
   if(type.equals("zone") && tab.equals("Oleadas")){action(names,actions,"Probar encuentro",()->send("test"));action(names,actions,"Detener encuentro",()->send("cancel"));}
   if(type.equals("npc") && tab.equals("Apariencia"))action(names,actions,"Mover a mi posición",()->send("move"));
   if(type.equals("npc") && tab.equals("Acción"))action(names,actions,"Más botones…",()->minecraft.setScreen(new NpcButtonsScreen(this,values.getOrDefault("extraActions","[]"),v->{values.put("extraActions",v);minecraft.setScreen(this);})));
   if(type.equals("npc") && tab.equals("Acción") && !id.isEmpty())action(names,actions,"Restablecer usos",()->confirm("¿Restablecer usos?","Borra esperas y revisiones. Comprueba antes las entregas anteriores.","reset_npc_actions"));
  }
  int count=names.size(),cols=Math.min(3,count),aw=(w-24-(cols-1)*6)/cols,ay=top+h-58-(count>3?24:0);
  for(i=0;i<count;i++){int index=i;boolean anchored=type.equals("zone") && names.get(i).equals("Crear zona de dungeon") && data.has("zonePreview") && data.getAsJsonObject("zonePreview").has("center") && !data.getAsJsonObject("zonePreview").get("center").isJsonNull();var actionButton=button(left+12+(i%cols)*(aw+6),ay+(i/cols)*24,aw,anchored?"Centro fijado":names.get(i),actions.get(index));if(anchored)actionButton.active=false;}
  if(type.equals("loot") && tab.equals("Objetos")){button(left+12,top+75,w-114,"Seleccionar objeto de la tabla",this::selectEntry);button(left+w-96,top+75,84,"Quitar objeto",()->confirm("¿Quitar objeto?","Se eliminará solo la entrada seleccionada.","remove_entry"));}
  if(!id.isEmpty() || type.equals("chest"))button(left+12,top+h-28,86,"Eliminar…",()->confirm("¿Eliminar?","Sus registros de entregas se conservan.","delete_confirmed"));
  if(pages>1){button(left+w/2-43,top+h-28,35,"<",()->{page=Math.max(0,page-1);rebuildWidgets();}).active=page>0;button(left+w/2+8,top+h-28,35,">",()->{page=Math.min(pages-1,page+1);rebuildWidgets();}).active=page+1<pages;}
  button(left+w-88,top+h-28,76,"Volver",this::back);
 }
 private void field(String key,int x,int y,int size){
  if(key.equals("text") && type.equals("npc"))return;
  labels.put(key,new int[]{x,y-11,size});
  if(key.equals("entity")){button(x,y,size,pretty(values.get(key)),()->minecraft.setScreen(new EntitySelectorScreen(this,v->{values.put(key,v);if(key.equals("noCooldown") && v.equals("false") && values.getOrDefault("minutes","0").equals("0"))values.put("minutes","10");minecraft.setScreen(this);})));return;}
  if(key.equals("loot") || key.equals("completionLoot")){button(x,y,size,values.getOrDefault(key,"").isBlank()?"Sin recompensa":pretty(values.get(key)),()->choose("loot","Elegir recompensa",true,v->values.put(key,v)));return;}
  if(key.equals("team")){button(x,y,size,teamCount()+" tipos · Elegir mobs",()->minecraft.setScreen(new TeamScreen(this,choices("mobs"),values.getOrDefault("team",""),v->{values.put("team",v);minecraft.setScreen(this);})));return;}
  if(Set.of("boss","enabled","category","slot","skin","noCooldown","hudEnabled").contains(key)){
   var options=new JsonArray();List<String> list=key.equals("skin")?com.ianblk.zianmanager.core.Definitions.NPC_SKINS:key.equals("category")?List.of("MOB","BOSS","CHEST"):key.equals("slot")?List.of("mainhand","offhand","head","chest","legs","feet"):List.of("false","true");
   for(String v:list){var o=new JsonObject();o.addProperty("id",v);o.addProperty("name",pretty(v));options.add(o);}
   button(x,y,size,pretty(values.get(key)),()->minecraft.setScreen(new ChoiceScreen(this,label(key),options,false,v->{values.put(key,v);if(key.equals("noCooldown") && v.equals("false") && values.getOrDefault("minutes","0").equals("0"))values.put("minutes","10");minecraft.setScreen(this);})));return;
  }
  boolean zoneSize=type.equals("zone") && Set.of("radiusX","radiusZ","above","below").contains(key);var box=new EditBox(font,zoneSize?x+26:x,y,zoneSize?size-52:size,20,Component.literal(label(key)));box.setMaxLength(key.equals("command")?2048:key.equals("effects") || key.equals("resetMessage") || key.equals("exhaustedMessage") || key.equals("warningMessage")?512:key.equals("worlds")?1024:128);box.setValue(values.getOrDefault(key,""));box.setResponder(v->{values.put(key,v);if(zoneSize)previewSize();});box.setTooltip(Tooltip.create(Component.literal(helpField(key))));if(key.equals("id") && !id.isEmpty() || key.equals("minutes") && values.getOrDefault("noCooldown","false").equals("true"))box.setEditable(false);inputs.put(key,box);addRenderableWidget(box);if(zoneSize){button(x,y,22,"−",()->stepSize(key,-1));button(x+size-22,y,22,"+",()->stepSize(key,1));}
 }
 private void stepSize(String key,int delta){try{int min=key.equals("below")?0:1,max=64;values.put(key,""+Math.max(min,Math.min(max,Integer.parseInt(values.get(key))+delta)));previewSize();rebuildWidgets();}catch(NumberFormatException ignored){}}
 private void previewSize(){if(!data.has("zonePreview"))return;var preview=data.getAsJsonObject("zonePreview").deepCopy();if(!preview.has("center") || preview.get("center").isJsonNull())return;try{var c=preview.getAsJsonObject("center");var center=new com.ianblk.zianmanager.core.Definitions.Point(c.get("x").getAsDouble(),c.get("y").getAsDouble(),c.get("z").getAsDouble(),0);var bounds=com.ianblk.zianmanager.core.CenteredZone.bounds(center,Integer.parseInt(values.get("radiusX")),Integer.parseInt(values.get("radiusZ")),Integer.parseInt(values.get("above")),Integer.parseInt(values.get("below")));preview.add("first",com.ianblk.zianmanager.core.AtomicJson.GSON.toJsonTree(bounds.first()));preview.add("second",com.ianblk.zianmanager.core.AtomicJson.GSON.toJsonTree(bounds.second()));preview.addProperty("preview",true);var wrapper=new JsonObject();wrapper.add("zonePreview",preview);ZonePreview.accept(wrapper);}catch(Exception ignored){}}
 private void listWidgets(){var entries=data.getAsJsonArray("entries");int per=Math.max(1,(h-86)/26),pages=Math.max(1,(entries.size()+per-1)/per);page=Math.min(page,pages-1);
  for(int i=page*per;i<Math.min(entries.size(),(page+1)*per);i++){var e=entries.get(i).getAsJsonObject();String target=e.has("id")?e.get("id").getAsString():"";String text=type.equals("root")?EditorSections.title(target.equals("loot")?"lootlist":target):e.get("name").getAsString();var b=button(left+12,top+62+(i-page*per)*26,w-24,text,()->{if(type.equals("claim"))return;request(type.equals("root")?(target.equals("loot")?"lootlist":target):type.equals("lootlist")?"loot":type.substring(0,type.length()-1),type.equals("root")?"":target);});if(type.equals("claim"))b.active=false;}
  button(left+12,top+h-28,30,"<",()->{page=Math.max(0,page-1);rebuildWidgets();}).active=page>0;button(left+46,top+h-28,30,">",()->{page=Math.min(pages-1,page+1);rebuildWidgets();}).active=page+1<pages;
  if(type.equals("chests"))button(left+84,top+h-28,w-184,"Obtener cofre",()->{if(minecraft.getConnection()!=null)minecraft.getConnection().sendCommand("zianmanager givechest");onClose();});
  if(type.equals("claim"))button(left+84,top+h-28,w-184,"Recibir recompensas",()->send("claim"));else if(!type.equals("root") && !type.equals("chests"))button(left+84,top+h-28,w-184,"Crear nuevo",()->{LAST_TAB.remove(type.equals("lootlist")?"loot":type.substring(0,type.length()-1));request(type.equals("lootlist")?"loot":type.substring(0,type.length()-1),"");});
  button(left+w-88,top+h-28,76,type.equals("root")?"Cerrar":"Volver",this::back);
 }
 private void selectEntry(){minecraft.setScreen(new EntriesScreen(this,data.getAsJsonArray("entries"),index->{values.put("entry",index);for(var e:data.getAsJsonArray("entries")){var o=e.getAsJsonObject();if(o.get("id").getAsString().equals(index))for(String k:List.of("weight","min","max"))if(o.has(k))values.put(k,o.get(k).getAsString());}minecraft.setScreen(this);}));}
 private JsonArray choices(String kind){return data.has("choices")?data.getAsJsonObject("choices").getAsJsonArray(kind):new JsonArray();}
 private void choose(String kind,String title,boolean none,java.util.function.Consumer<String> accept){minecraft.setScreen(new ChoiceScreen(this,title,choices(kind),none,v->{accept.accept(v);minecraft.setScreen(this);}));}
 private int teamCount(){return (int)Arrays.stream(values.getOrDefault("team","").split(",")).filter(v->!v.isBlank()).count();}
 private static void action(List<String> names,List<Runnable> actions,String name,Runnable action){names.add(name);actions.add(action);}
 private void confirm(String title,String message,String operation){minecraft.setScreen(new ManagerConfirmScreen(ok->{if(ok)send(operation);else minecraft.setScreen(this);},Component.literal(title),Component.literal(message)));}
 private int percent(String key,int fallback){try{return Math.max(0,Math.min(100,Integer.parseInt(values.getOrDefault(key,""+fallback))));}catch(Exception ignored){return fallback;}}
 private void back(){if(type.equals("root")){onClose();return;}request(list() || type.equals("time")?"root":type.equals("loot")?"lootlist":type+"s","");}
 private void request(String section,String target){PacketDistributor.sendToServer(new ManagerNetwork.Request(section,target));}
 private void send(String operation){var fields=new JsonObject();values.forEach(fields::addProperty);PacketDistributor.sendToServer(new ManagerNetwork.Action(token,operation,fields.toString()));}
 private Button button(int x,int y,int size,String text,Runnable action){return addRenderableWidget(themed(x,y,size,20,Component.literal(text),b->action.run()));}
 private static String pretty(String value){if(value==null)return "";return switch(value){case "true"->"Sí";case "false"->"No";case "MOB"->"Mobs";case "BOSS"->"Jefes";case "CHEST"->"Cofres";case "mainhand"->"Mano principal";case "offhand"->"Mano secundaria";case "head"->"Cabeza";case "chest"->"Pecho";case "legs"->"Piernas";case "feet"->"Pies";default->value.replace("minecraft:","").replace("_"," ");};}
 private static String label(String key){return switch(key){case "hudX"->"Posición horizontal (0–100%)";case "hudY"->"Posición vertical (0–100%)";case "hudEnabled"->"Mostrar temporizador";case "warningMessage"->"Aviso previo (usa {time})";case "resetMessage"->"Anuncio al renovar (00:01)";case "exhaustedMessage"->"Aviso de tiempo agotado";case "worlds"->"Mundos de dungeon (separados por coma)";case "timezone"->"Zona horaria del reinicio";case "defaultWeekday","vipWeekday"->"Lunes a viernes (minutos)";case "defaultWeekend","vipWeekend"->"Fin de semana (minutos)";case "vipPermission"->"Permiso de VIP";case "bypassPermission"->"Permiso sin límite";case "exitCommand"->"Destino / comando de salida";case "radiusX"->"Bloques a cada lado (X)";case "radiusZ"->"Bloques a cada lado (Z)";case "above"->"Bloques por encima";case "below"->"Bloques por debajo";case "id"->"Nombre / referencia";case "name"->"Nombre visible";case "entity"->"Tipo de mob";case "health"->"Vida máxima";case "damage"->"Daño de ataque";case "armor"->"Armadura";case "toughness"->"Dureza de armadura";case "knockback"->"Resistencia al empuje (0–1)";case "boss"->"¿Es un jefe?";case "category"->"Usar para";case "rolls"->"Cuántos objetos sortear";case "weight"->"Probabilidad relativa";case "min"->"Cantidad mínima";case "max"->"Cantidad máxima";case "table"->"Tabla externa (opcional)";case "team"->"Tipos de mob de la zona";case "waves"->"Número de oleadas";case "pauseSeconds"->"Pausa entre oleadas (seg)";case "respawnSeconds"->"Volver a aparecer (seg)";case "enabled"->"¿Activar?";case "noCooldown"->"Sin tiempo de reutilización";case "minutes"->"Renovar loot (minutos)";case "effects"->"Formato manual de efectos";case "skin"->"Apariencia";case "button"->"Texto del botón";case "command"->"Comando del botón";case "cooldownSeconds"->"Espera por jugador (seg)";case "slot"->"Equipar en";case "loot","completionLoot"->"Recompensas";default->key;};}
 private static String helpField(String key){return switch(key){case "hudX"->"Posición horizontal (0–100%)";case "hudY"->"Posición vertical (0–100%)";case "hudEnabled"->"Mostrar temporizador";case "warningMessage"->"Aviso previo (usa {time})";case "resetMessage"->"Anuncio al renovar (00:01)";case "exhaustedMessage"->"Aviso de tiempo agotado";case "worlds"->"Mundos de dungeon (separados por coma)";case "timezone"->"Zona horaria del reinicio";case "defaultWeekday","vipWeekday"->"Lunes a viernes (minutos)";case "defaultWeekend","vipWeekend"->"Fin de semana (minutos)";case "vipPermission"->"Permiso de VIP";case "bypassPermission"->"Permiso sin límite";case "exitCommand"->"bed: cama válida o spawn; worldspawn: spawn del mundo; o comando con {player}.";case "radiusX"->"Bloques a cada lado (X)";case "radiusZ"->"Bloques a cada lado (Z)";case "above"->"Bloques por encima";case "below"->"Bloques por debajo";case "id"->"Se crea una referencia automáticamente. Puedes cambiarla antes de guardar: minúsculas, números y _.";case "weight"->"Más peso significa más probabilidad. El porcentaje se muestra en la lista de objetos.";case "command"->"Usa {player} para el nombre del jugador. Ejemplo: minecraft:tp {player} 100 70 100";case "effects"->"Opcional. El selector de Efectos permite configurarlos sin escribir este formato.";default->label(key);};}
 private String help(){if(list())return type.equals("root")?"Elige qué quieres configurar.":type.equals("chests")?"Coloca un cofre y usa Shift + clic derecho para configurarlo.":"Selecciona uno para editarlo o crea uno nuevo.";
  if(type.equals("loot"))return tab.equals("Objetos")?"Sostén un objeto para añadirlo; elige uno de la lista para editarlo.":tab.equals("Avanzado")?"Opcional: usa una tabla externa en lugar de objetos propios.":"Elige el tipo de recompensa y cuántos objetos se sortean.";
  if(type.equals("time"))return tab.equals("Mundos")?"Selecciona tus mundos de dungeon; el tiempo se comparte entre ellos.":tab.equals("Rangos")?"Añade permisos y límites. OP o bypass tienen tiempo ilimitado.":tab.equals("Mensajes")?"Aviso al agotarse y anuncio diario a las 00:01 de la zona horaria configurada.":"Los límites se indican en minutos. Guarda para aplicar los cambios.";
  if(type.equals("zone"))return tab.equals("Ubicación")?"Centro fijo. Los mobs aparecen automáticamente dentro del área.":tab.equals("Tamaño")?"Radio 3 = 7×7. Vista previa en vivo; Aplicar tamaño guarda los cambios.":tab.equals("General")?"Selecciona al menos un tipo. Inicio: 1–3; +2 por jugador extra; máximo 8.":"Define las oleadas, las pausas y el tiempo para repetir la dungeon.";
  if(type.equals("mob"))return tab.equals("Equipo")?"Sostén un objeto, elige la ranura y pulsa Copiar objeto de mano.":tab.equals("Avanzado")?"Opcional. Los ajustes habituales están en las otras secciones.":tab.equals("Efectos")?"Selecciona efectos, su nivel y cuánto duran, sin escribir IDs.":"Configura esta sección y guarda. Puedes volver a editar después.";
  if(type.equals("npc"))return tab.equals("Acción")?"Opcional: un botón ejecuta tu comando. {player} es el jugador.":tab.equals("Diálogo")?"Escribe el diálogo; puedes usar varias líneas.":"Elige nombre y skin; el personaje aparece en tu posición.";
  return "Selecciona sus recompensas y cada cuánto se renuevan.";
 }
 @Override public void render(GuiGraphics g,int mx,int my,float dt){panel(g,left,top,w,h);g.drawString(font,font.plainSubstrByWidth(help(),w-24),left+12,top+(list()?38:61),0xFFAAAAAA);
  if(!list() && !(type.equals("loot") && tab.equals("Objetos"))){String notice=data.has("notice")?data.get("notice").getAsString():"";g.drawString(font,font.plainSubstrByWidth(notice,w-24),left+12,top+76,0xFFF7E2AC);}
  for(var e:labels.entrySet()){var pos=e.getValue();g.drawString(font,font.plainSubstrByWidth(label(e.getKey()),pos[2]),pos[0],pos[1],0xFFDDDDDD);}super.render(g,mx,my,dt);
 }
}
