package lat.rassvet.worlds;
import org.bukkit.Bukkit;
import org.bukkit.command.*;
import org.bukkit.plugin.java.JavaPlugin;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.function.Consumer;
import java.lang.reflect.*;
import org.bukkit.event.*;
import org.bukkit.event.player.PlayerTeleportEvent;
public final class CasasTools extends JavaPlugin implements CommandExecutor,Listener {
 private boolean ready;
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void protect(PlayerTeleportEvent e){if(!ready && e.getTo()!=null && e.getTo().getWorld().getKey().toString().equals("rassvet:casas")){e.setCancelled(true);e.getPlayer().sendMessage("§eMundo Casas está temporalmente en configuración.");}}
 public void onEnable(){getCommand("casastools").setExecutor(this);getServer().getPluginManager().registerEvents(this,this);try{
 Object server=Bukkit.getServer().getClass().getMethod("getServer").invoke(Bukkit.getServer()),access=call(server,"registryAccess");var rk=cls("net.minecraft.resources.ResourceKey");Object registry=cls("net.minecraft.core.RegistryAccess").getMethod("registryOrThrow",rk).invoke(access,cls("net.minecraft.core.registries.Registries").getField("BIOME").get(null));Class<?> biomeClass=cls("net.minecraft.world.level.biome.Biome"),infoClass=cls("net.neoforged.neoforge.common.world.ModifiableBiomeInfo");var field=infoClass.getDeclaredField("modifiedBiomeInfo");field.setAccessible(true);int count=0;
 for(Object entry:(Set<?>)cls("net.minecraft.core.Registry").getMethod("entrySet").invoke(registry)){var e=(Map.Entry<?,?>)entry;if(!key(e.getKey()).startsWith("rassvet_casas:"))continue;Object info=biomeClass.getMethod("modifiableBiomeInfo").invoke(e.getValue());field.set(info,infoClass.getMethod("getOriginalBiomeInfo").invoke(info));count++;}
 var world=Bukkit.getWorld("casas");if(world!=null){Object handle=world.getClass().getMethod("getHandle").invoke(world),chunkSource=call(handle,"getChunkSource"),generator=call(chunkSource,"getGenerator"),source=call(generator,"getBiomeSource");var method=cls("net.minecraft.world.level.biome.MultiNoiseBiomeSource").getDeclaredMethod("parameters");method.setAccessible(true);Object parameters=method.invoke(source);int flags=0;for(var f:parameters.getClass().getDeclaredFields())if(f.getType()==boolean.class && (f.getName().equals("initialized") || f.getName().endsWith("$initialized") || f.getName().equals("treesPopulated") || f.getName().endsWith("$treesPopulated"))){f.setAccessible(true);f.setBoolean(parameters,false);flags++;}Set<Object> exactBiomes=new LinkedHashSet<>();for(Object pair:(List<?>)call(parameters,"values")){Object holder=cls("com.mojang.datafixers.util.Pair").getMethod("getSecond").invoke(pair);Object holderKey=((Optional<?>)cls("net.minecraft.core.Holder").getMethod("unwrapKey").invoke(holder)).orElseThrow();if(!key(holderKey).startsWith("rassvet_casas:"))throw new IllegalStateException("Foreign biome in Casas climate map");exactBiomes.add(holder);}var possible=cls("net.minecraft.world.level.biome.BiomeSource").getDeclaredField("possibleBiomes");possible.setAccessible(true);possible.set(source,(java.util.function.Supplier<Set<Object>>)(()->Collections.unmodifiableSet(exactBiomes)));
 if(flags<2)throw new IllegalStateException("TerraBlender isolation flags not found");if((boolean)cls("terrablender.worldgen.IExtendedParameterList").getMethod("isInitialized").invoke(parameters))throw new IllegalStateException("Casas still using global regions");Object ownData=cls("net.minecraft.server.level.ServerLevel").getField("K").get(handle);Class<?> infoType=cls("com.mohistmc.youer.neoforge.YouerDerivedWorldInfo");Field delegate=infoType.getDeclaredField("derivedWorldInfo");delegate.setAccessible(true);Object originalData=delegate.get(ownData);Field settings=cls("net.minecraft.world.level.storage.PrimaryLevelData").getDeclaredField("settings");settings.setAccessible(true);Method difficultyGetter=cls("net.minecraft.world.level.LevelSettings").getMethod("difficulty"),difficultySetter=cls("net.minecraft.world.level.storage.PrimaryLevelData").getMethod("setDifficulty",cls("net.minecraft.world.Difficulty"));Class<?> dataInterface=cls("net.minecraft.world.level.storage.ServerLevelData");Class<?> difficultyType=cls("net.minecraft.world.Difficulty");Object ownDifficulty=Proxy.newProxyInstance(dataInterface.getClassLoader(),new Class<?>[]{dataInterface},(proxy,m,args)->{if(m.getReturnType()==difficultyType && m.getParameterCount()==0)return difficultyGetter.invoke(settings.get(ownData));try{return m.invoke(originalData,args);}catch(InvocationTargetException error){throw error.getCause();}});delegate.set(ownData,ownDifficulty);Field levelDataField=cls("net.minecraft.world.level.Level").getDeclaredField("levelData"),serverDataField=cls("net.minecraft.server.level.ServerLevel").getDeclaredField("serverLevelData");levelDataField.setAccessible(true);serverDataField.setAccessible(true);levelDataField.set(handle,ownDifficulty);serverDataField.set(handle,ownDifficulty);world.setDifficulty(org.bukkit.Difficulty.NORMAL);world.setSpawnFlags(true,true);
 Object structureState=call(chunkSource,"getGeneratorState");Field structureSets=structureState.getClass().getDeclaredField("possibleStructureSets");structureSets.setAccessible(true);structureSets.set(structureState,List.of());for(String fieldName:List.of("placementsForStructure","ringPositions")){Field stateField=structureState.getClass().getDeclaredField(fieldName);stateField.setAccessible(true);((Map<?,?>)stateField.get(structureState)).clear();}Field generated=structureState.getClass().getDeclaredField("hasGeneratedPositions");generated.setAccessible(true);generated.setBoolean(structureState,false);
 getServer().getScheduler().runTask(this,()->{world.setDifficulty(org.bukkit.Difficulty.NORMAL);world.setSpawnFlags(true,true);});getLogger().info("Casas owns NORMAL difficulty; primary and other dimensions retain their existing level data.");
 getLogger().info("Casas explicit climate map active; global TerraBlender regions disabled only for this world.");}
 Class<?> registryClass=cls("net.minecraft.core.Registry"),holderClass=cls("net.minecraft.core.Holder"),pairClass=cls("com.mojang.datafixers.util.Pair");Map<Object,List<Object>> tags=new LinkedHashMap<>();for(Object pair:((java.util.stream.Stream<?>)registryClass.getMethod("getTags").invoke(registry)).toList()){Object tag=pairClass.getMethod("getFirst").invoke(pair),set=pairClass.getMethod("getSecond").invoke(pair);List<Object> holders=new ArrayList<>();for(Object holder:(Iterable<?>)set)holders.add(holder);tags.put(tag,holders);}
 Map<String,Object> holdersById=new HashMap<>();for(Object entry:(Set<?>)registryClass.getMethod("entrySet").invoke(registry)){var e=(Map.Entry<?,?>)entry;Object holder=((Optional<?>)registryClass.getMethod("getHolder",rk).invoke(registry,e.getKey())).orElseThrow();holdersById.put(key(e.getKey()),holder);}
 int pokemonTags=0;for(var tag:tags.entrySet()){String tagId=cls("net.minecraft.tags.TagKey").getMethod("location").invoke(tag.getKey()).toString();if(!tagId.startsWith("cobblemon:"))continue;Set<String> originalIds=new HashSet<>();for(Object holder:tag.getValue()){Object key=((Optional<?>)holderClass.getMethod("unwrapKey").invoke(holder)).orElseThrow();originalIds.add(key(key));}int added=0;for(var e:holdersById.entrySet()){String id=e.getKey(),original=id.startsWith("rassvet_casas:vanilla/")?"minecraft:"+id.substring("rassvet_casas:vanilla/".length()):id.startsWith("rassvet_casas:bop/")?"biomesoplenty:"+id.substring("rassvet_casas:bop/".length()):null;if(original!=null && originalIds.contains(original) && !tag.getValue().contains(e.getValue())){tag.getValue().add(e.getValue());added++;}}if(added>0)pokemonTags++;}registryClass.getMethod("bindTags",Map.class).invoke(registry,tags);getLogger().info("Casas Cobblemon spawn classifications preserved in "+pokemonTags+" tags; structure generation disabled only for Casas.");
 ready=world!=null && count==114;getLogger().info("Casas generation isolated from biome injections: "+count+" cloned biomes restored to their filtered datapack definitions.");
 }catch(Exception|LinkageError e){getLogger().log(java.util.logging.Level.SEVERE,"Casas isolation failed; keep world closed",e);}}
 static Class<?> cls(String n)throws Exception{return Class.forName(n);}
 static Object call(Object o,String method)throws Exception{return o.getClass().getMethod(method).invoke(o);}
 static String key(Object key)throws Exception{return call(key,"location").toString();}
 static JsonElement encode(Object codec,Object ops,Object value)throws Exception{Object result=cls("com.mojang.serialization.Codec").getMethod("encodeStart",cls("com.mojang.serialization.DynamicOps"),Object.class).invoke(codec,ops,value);return (JsonElement)cls("com.mojang.serialization.DataResult").getMethod("getOrThrow").invoke(result);}
 static JsonArray points(List<Object> entries,Object jsonOps)throws Exception{JsonArray out=new JsonArray();Object codec=cls("net.minecraft.world.level.biome.Climate$ParameterPoint").getField("CODEC").get(null);for(Object entry:entries){var pair=cls("com.mojang.datafixers.util.Pair");JsonObject p=new JsonObject();p.add("parameters",encode(codec,jsonOps,pair.getMethod("getFirst").invoke(entry)));p.addProperty("biome",key(pair.getMethod("getSecond").invoke(entry)));out.add(p);}return out;}
 public boolean onCommand(CommandSender sender,Command cmd,String label,String[] args){if(!sender.hasPermission("rassvet.admin"))return true;
  try{Object server=Bukkit.getServer().getClass().getMethod("getServer").invoke(Bukkit.getServer()),access=call(server,"registryAccess");Class<?> rk=cls("net.minecraft.resources.ResourceKey"),ra=cls("net.minecraft.core.RegistryAccess"),reg=cls("net.minecraft.core.Registry");Object biomeKey=cls("net.minecraft.core.registries.Registries").getField("BIOME").get(null),biomes=ra.getMethod("registryOrThrow",rk).invoke(access,biomeKey);Object jsonOps=cls("com.mojang.serialization.JsonOps").getField("INSTANCE").get(null);Object ops=cls("net.minecraft.resources.RegistryOps").getMethod("create",cls("com.mojang.serialization.DynamicOps"),cls("net.minecraft.core.HolderLookup$Provider")).invoke(null,jsonOps,access);Files.createDirectories(getDataFolder().toPath());
   if(args.length==1 && args[0].equals("export")){
    JsonObject out=new JsonObject(),all=new JsonObject(),regions=new JsonObject();Object codec=cls("net.minecraft.world.level.biome.Biome").getField("DIRECT_CODEC").get(null);
    for(Object entry:(Set<?>)reg.getMethod("entrySet").invoke(biomes)){var e=(Map.Entry<?,?>)entry;String id=key(e.getKey());if(id.startsWith("minecraft:") || id.startsWith("biomesoplenty:"))all.add(id,encode(codec,ops,e.getValue()));}
    var entries=new ArrayList<Object>();Consumer<Object> sink=entries::add;var vanillaClass=cls("net.minecraft.world.level.biome.OverworldBiomeBuilder");Object vanilla=vanillaClass.getConstructor().newInstance();var method=vanillaClass.getDeclaredMethod("addBiomes",Consumer.class);method.setAccessible(true);method.invoke(vanilla,sink);regions.add("vanilla",points(entries,jsonOps));
    for(String kind:List.of("Primary","Secondary","Rare")){entries.clear();var c=cls("biomesoplenty.worldgen.BOPOverworldRegion"+kind);var region=c.getConstructor(int.class).newInstance(1);c.getMethod("addBiomes",reg,Consumer.class).invoke(region,biomes,sink);regions.add(kind.toLowerCase(Locale.ROOT),points(entries,jsonOps));}
    out.add("biomes",all);out.add("regions",regions);
    Object nk=cls("net.minecraft.core.registries.Registries").getField("NOISE_SETTINGS").get(null),noise=ra.getMethod("registryOrThrow",rk).invoke(access,nk);Object location=cls("net.minecraft.resources.ResourceLocation").getMethod("parse",String.class).invoke(null,"minecraft:overworld"),settings=reg.getMethod("get",cls("net.minecraft.resources.ResourceLocation")).invoke(noise,location);out.add("noise_settings",encode(cls("net.minecraft.world.level.levelgen.NoiseGeneratorSettings").getField("DIRECT_CODEC").get(null),ops,settings));
    Object rule=cls("biomesoplenty.worldgen.BOPSurfaceRuleData").getMethod("overworld").invoke(null);out.add("bop_surface_rule",encode(cls("net.minecraft.world.level.levelgen.SurfaceRules$RuleSource").getField("CODEC").get(null),ops,rule));
    Object pk=cls("net.minecraft.core.registries.Registries").getField("PLACED_FEATURE").get(null),placed=ra.getMethod("registryOrThrow",rk).invoke(access,pk);JsonArray featureIds=new JsonArray();for(Object id:(Set<?>)reg.getMethod("keySet").invoke(placed))featureIds.add(id.toString());out.add("placed_features",featureIds);
    Files.writeString(getDataFolder().toPath().resolve("worldgen-export.json"),new GsonBuilder().setPrettyPrinting().create().toJson(out));sender.sendMessage("Casas export ready: "+all.size()+" biomes and native surface rules.");
   }else if(args.length==1 && args[0].equals("audit")){
    JsonObject out=new JsonObject();var holderClass=cls("net.minecraft.core.Holder");for(Object entry:(Set<?>)reg.getMethod("entrySet").invoke(biomes)){var e=(Map.Entry<?,?>)entry;String id=key(e.getKey());if(!id.startsWith("rassvet_casas:"))continue;JsonArray features=new JsonArray();Object gen=cls("net.minecraft.world.level.biome.Biome").getMethod("getGenerationSettings").invoke(e.getValue());for(Object step:(List<?>)call(gen,"features"))for(Object holder:(Iterable<?>)step){Object k=((Optional<?>)holderClass.getMethod("unwrapKey").invoke(holder)).orElse(null);features.add(k==null?"UNREGISTERED_INJECTION":key(k));}out.add(id,features);}
    JsonArray matching=new JsonArray();Object sk=cls("net.minecraft.core.registries.Registries").getField("STRUCTURE").get(null),structures=ra.getMethod("registryOrThrow",rk).invoke(access,sk);
    for(Object entry:(Set<?>)reg.getMethod("entrySet").invoke(structures)){var e=(Map.Entry<?,?>)entry;Object allowed=cls("net.minecraft.world.level.levelgen.structure.Structure").getMethod("biomes").invoke(e.getValue());boolean found=false;
     for(Object bEntry:(Set<?>)reg.getMethod("entrySet").invoke(biomes)){var b=(Map.Entry<?,?>)bEntry;if(!key(b.getKey()).startsWith("rassvet_casas:"))continue;Object holder=((Optional<?>)reg.getMethod("getHolder",rk).invoke(biomes,b.getKey())).orElseThrow();if((boolean)cls("net.minecraft.core.HolderSet").getMethod("contains",holderClass).invoke(allowed,holder)){found=true;break;}}
     if(found)matching.add(key(e.getKey()));
    }
    JsonObject report=new JsonObject();report.add("biomes",out);report.add("structuresMatching",matching);JsonArray worldBiomes=new JsonArray();var world=Bukkit.getWorld("casas");if(world!=null){Object handle=world.getClass().getMethod("getHandle").invoke(world),chunkSource=call(handle,"getChunkSource"),generator=call(chunkSource,"getGenerator"),source=call(generator,"getBiomeSource");for(Object h:(Set<?>)cls("net.minecraft.world.level.biome.BiomeSource").getMethod("possibleBiomes").invoke(source)){Object k=((Optional<?>)holderClass.getMethod("unwrapKey").invoke(h)).orElseThrow();worldBiomes.add(key(k));}var pm=cls("net.minecraft.world.level.biome.MultiNoiseBiomeSource").getDeclaredMethod("parameters");pm.setAccessible(true);Object params=pm.invoke(source);report.addProperty("globalTerraBlenderRegions",(boolean)cls("terrablender.worldgen.IExtendedParameterList").getMethod("isInitialized").invoke(params));JsonObject sampled=new JsonObject();Object randomState=call(chunkSource,"randomState"),sampler=call(randomState,"sampler");var noiseMethod=cls("net.minecraft.world.level.biome.BiomeSource").getMethod("getNoiseBiome",int.class,int.class,int.class,cls("net.minecraft.world.level.biome.Climate$Sampler"));for(int x:new int[]{-4096,-2048,-1024,-512,0,512,1024,2048,4096})for(int z:new int[]{-4096,-2048,-1024,-512,0,512,1024,2048,4096}){Object h=noiseMethod.invoke(source,x/4,18,z/4,sampler),k=((Optional<?>)holderClass.getMethod("unwrapKey").invoke(h)).orElseThrow();String id=key(k);sampled.addProperty(id,sampled.has(id)?sampled.get(id).getAsInt()+1:1);}report.add("sampledBiomes",sampled);report.addProperty("difficulty",world.getDifficulty().name());report.addProperty("enabledStructureSets",((List<?>)call(call(chunkSource,"getGeneratorState"),"possibleStructureSets")).size());report.addProperty("worldName",world.getName());report.addProperty("worldKey",world.getKey().toString());report.addProperty("worldFolder",world.getWorldFolder().getAbsolutePath());}report.add("worldBiomes",worldBiomes);Files.writeString(getDataFolder().toPath().resolve("casas-audit.json"),new GsonBuilder().setPrettyPrinting().create().toJson(report));sender.sendMessage("Casas audit: "+out.size()+" isolated biomes; matching structures="+matching.size());
   }else sender.sendMessage("casastools export|audit");
  }catch(Exception|LinkageError e){getLogger().log(java.util.logging.Level.SEVERE,"Casas tools failed",e);sender.sendMessage("No se pudo completar la comprobación.");}return true;
 }
}
