name: RassvetRules
version: 1.0.5
main: lat.rassvet.rules.RassvetRules
api-version: '1.21'
depend: [EternalCore, LuckPerms, CommandWhitelist]
softdepend: [WorldEdit]
commands:
  rassvet:
    description: Menú de TPA y utilidades de Rassvet
permissions:
  rassvet.admin:
    default: op
  rassvet.flight.bypass:
    default: op
  rassvet.tpa:
    default: false
  rassvet.lobbyflight:
    default: op

  rassvet.time:
    default: false
  rassvet.shop:
    default: false
