package com.ianblk.zianmanager;
import net.minecraft.world.item.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.core.component.DataComponents;
import net.minecraft.server.level.*;
import net.minecraft.world.level.block.Blocks;
public final class ImportedGearSmoke {
 private static double stat(ItemStack stack,net.minecraft.core.Holder<net.minecraft.world.entity.ai.attributes.Attribute> attr){return stack.get(DataComponents.ATTRIBUTE_MODIFIERS).modifiers().stream().filter(e->e.attribute().equals(attr)).mapToDouble(e->e.modifier().amount()).sum();}
 private static final class ArmorProbe extends net.minecraft.world.entity.monster.Zombie{ArmorProbe(ServerLevel level){super(EntityType.ZOMBIE,level);}void damageHelmet(){doHurtEquipment(level().damageSources().generic(),8,EquipmentSlot.HEAD);}}
 public static void verify(ServerPlayer player){var registry=player.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.ENCHANTMENT);var protection=registry.getOrThrow(Enchantments.PROTECTION);var respiration=registry.getOrThrow(Enchantments.RESPIRATION);var aqua=registry.getOrThrow(Enchantments.AQUA_AFFINITY);var unbreaking=registry.getOrThrow(Enchantments.UNBREAKING);var mending=registry.getOrThrow(Enchantments.MENDING);var sharpness=registry.getOrThrow(Enchantments.SHARPNESS);var efficiency=registry.getOrThrow(Enchantments.EFFICIENCY);var fortune=registry.getOrThrow(Enchantments.FORTUNE);var silk=registry.getOrThrow(Enchantments.SILK_TOUCH);
  for(String id:ImportedGear.HATS){var stack=new ItemStack(ManagerEquipment.item(id));if(!(stack.getItem() instanceof ArmorItem armor) || armor.getEquipmentSlot()!=EquipmentSlot.HEAD || stack.getMaxDamage()!=new ItemStack(Items.NETHERITE_HELMET).getMaxDamage() || stat(stack,Attributes.ARMOR)!=4 || stat(stack,Attributes.ARMOR_TOUGHNESS)!=3 || stat(stack,Attributes.KNOCKBACK_RESISTANCE)!=0.1)throw new IllegalStateException("Helmet statistics or slot incorrect: "+id);for(var enchant:java.util.List.of(protection,respiration,aqua,unbreaking,mending))if(!stack.supportsEnchantment(enchant))throw new IllegalStateException("Helmet enchantment rejected: "+id);var probe=new ArmorProbe(player.serverLevel());probe.setItemSlot(EquipmentSlot.HEAD,stack);probe.damageHelmet();if(stack.getDamageValue()!=2)throw new IllegalStateException("Hat does not wear like real armor: "+id);}
  for(String id:ImportedGear.TOOLS){var stack=new ItemStack(ManagerEquipment.item(id));var vanilla=new ItemStack(ImportedGear.VANILLA.get(id));if(vanilla.isEmpty() || stack.getMaxDamage()!=75 || stat(stack,Attributes.ATTACK_DAMAGE)!=stat(vanilla,Attributes.ATTACK_DAMAGE)+1 || stat(stack,Attributes.ATTACK_SPEED)!=stat(vanilla,Attributes.ATTACK_SPEED) || stack.getItem().getEnchantmentValue()!=vanilla.getItem().getEnchantmentValue())throw new IllegalStateException("Vanilla tool stats +1 / durability75 incorrect: "+id);for(var enchant:java.util.List.of(unbreaking,mending))if(!stack.supportsEnchantment(enchant))throw new IllegalStateException("Durability enchantment rejected: "+id);if(id.endsWith("sword")){if(!stack.supportsEnchantment(sharpness))throw new IllegalStateException("Sword enchantment rejected");}else{for(var enchant:java.util.List.of(efficiency,fortune,silk))if(!stack.supportsEnchantment(enchant))throw new IllegalStateException("Mining enchantment rejected: "+id);var state=id.endsWith("axe") && !id.endsWith("pickaxe")?Blocks.OAK_LOG.defaultBlockState():id.endsWith("shovel")?Blocks.DIRT.defaultBlockState():Blocks.STONE.defaultBlockState();if(stack.getDestroySpeed(state)!=vanilla.getDestroySpeed(state))throw new IllegalStateException("Mining speed changed: "+id);}}
  ZianManager.LOGGER.info("Zian Manager imported gear smoke passed: 30 real helmets, armor4/toughness3/knockback0.1/netherite durability and wear, 20 vanilla tools+1/durability75, proper enchantments and mining speed");
 }
}
