package com.ianblk.zianmanager;
import com.ianblk.zianmanager.permission.ManagerPermissions;
import net.minecraft.commands.*;
import net.minecraft.commands.arguments.EntityArgument;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.RegisterCommandsEvent;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import java.util.UUID;
public final class ManagerCommands {
    public ManagerCommands(){NeoForge.EVENT_BUS.addListener(this::register);}
    private static int removeTime(CommandSourceStack source,net.minecraft.server.level.ServerPlayer player,int minutes){try{var limits=ManagerRuntime.get().dungeonTime();long removed=limits.removeTime(player,minutes);String message="Tiempo descontado a "+player.getGameProfile().getName()+": "+ZoneHolograms.countdown(removed*1000)+". Restante hoy: "+ZoneHolograms.countdown(limits.remaining(player)*1000);source.sendSuccess(()->Component.literal(message),true);if(removed>0)player.sendSystemMessage(Component.literal("Un administrador descontó "+ZoneHolograms.countdown(removed*1000)+" de tu tiempo de dungeon de hoy."));return 1;}catch(Exception error){source.sendFailure(Component.literal(error.getMessage()));return 0;}}
    private static int bonus(CommandSourceStack source,UUID player,int minutes){try{ManagerRuntime.get().dungeonTime().bonus(player,minutes);source.sendSuccess(()->Component.literal("Bono de "+minutes+" minutos añadido para "+(player==null?"todos":"el jugador")+"; vence al reinicio diario."),false);return 1;}catch(Exception error){source.sendFailure(Component.literal(error.getMessage()));return 0;}}
    private static int worldBonus(CommandSourceStack source,String profile,UUID player,int minutes){try{ManagerRuntime.get().worldTime().profile(profile).bonus(player,minutes);ManagerRuntime.get().worldTime().refresh();source.sendSuccess(()->Component.literal("Bono de "+minutes+" minutos para "+profile+" añadido; vence al reinicio diario."),false);return 1;}catch(Exception error){source.sendFailure(Component.literal(error.getMessage()));return 0;}}
    private void register(RegisterCommandsEvent event){event.getDispatcher().register(Commands.literal("zianmanager")
        .executes(c->{var player=c.getSource().getPlayerOrException();ManagerRuntime.get().request(player,"root","");return 1;})
        .then(Commands.literal("worldtime").requires(s->ManagerPermissions.allows(s,"admin",true)).then(Commands.argument("profile",StringArgumentType.word()).suggests((c,b)->SharedSuggestionProvider.suggest(ManagerRuntime.get().worldTime().profiles().keySet(),b))
         .then(Commands.literal("remove").then(Commands.argument("player",EntityArgument.player()).then(Commands.argument("minutes",IntegerArgumentType.integer(1,1440)).executes(c->{try{var p=EntityArgument.getPlayer(c,"player");var t=ManagerRuntime.get().worldTime().profile(StringArgumentType.getString(c,"profile"));long removed=t.removeTime(p,IntegerArgumentType.getInteger(c,"minutes"));ManagerRuntime.get().worldTime().refresh();c.getSource().sendSuccess(()->Component.literal("Descontado: "+ZoneHolograms.countdown(removed*1000)+". Restante: "+ZoneHolograms.countdown(t.remaining(p)*1000)),true);return 1;}catch(Exception error){c.getSource().sendFailure(Component.literal(error.getMessage()));return 0;}}))))
         .then(Commands.literal("bonus").then(Commands.literal("all").then(Commands.argument("minutes",IntegerArgumentType.integer(1,1440)).executes(c->worldBonus(c.getSource(),StringArgumentType.getString(c,"profile"),null,IntegerArgumentType.getInteger(c,"minutes")))))
          .then(Commands.argument("player",EntityArgument.player()).then(Commands.argument("minutes",IntegerArgumentType.integer(1,1440)).executes(c->worldBonus(c.getSource(),StringArgumentType.getString(c,"profile"),EntityArgument.getPlayer(c,"player").getUUID(),IntegerArgumentType.getInteger(c,"minutes"))))))))
        .then(Commands.literal("removetime").requires(s->ManagerPermissions.allows(s,"admin",true)).then(Commands.argument("player",EntityArgument.player()).then(Commands.argument("minutes",IntegerArgumentType.integer(1,1440)).executes(c->removeTime(c.getSource(),EntityArgument.getPlayer(c,"player"),IntegerArgumentType.getInteger(c,"minutes"))))))
        .then(Commands.literal("bonustime").requires(s->ManagerPermissions.allows(s,"admin",true))
         .then(Commands.literal("all").then(Commands.argument("minutes",IntegerArgumentType.integer(1,1440)).executes(c->bonus(c.getSource(),null,IntegerArgumentType.getInteger(c,"minutes")))))
         .then(Commands.literal("player").then(Commands.argument("player",EntityArgument.player()).then(Commands.argument("minutes",IntegerArgumentType.integer(1,1440)).executes(c->bonus(c.getSource(),EntityArgument.getPlayer(c,"player").getUUID(),IntegerArgumentType.getInteger(c,"minutes")))))))
        .then(Commands.literal("time").executes(c->{ManagerRuntime.get().worldTime().describe(c.getSource().getPlayerOrException(),null);return 1;}).then(Commands.argument("profile",StringArgumentType.word()).suggests((c,b)->SharedSuggestionProvider.suggest(ManagerRuntime.get().worldTime().profiles().keySet(),b)).executes(c->{ManagerRuntime.get().worldTime().describe(c.getSource().getPlayerOrException(),StringArgumentType.getString(c,"profile"));return 1;})))
        .then(Commands.literal("applyzone").requires(s->ManagerPermissions.allows(s,"admin",true)).then(Commands.argument("zone",StringArgumentType.word()).suggests((c,b)->SharedSuggestionProvider.suggest(ManagerRuntime.get().store().data().zones().keySet(),b)).executes(c->{try{ManagerRuntime.get().applyZone(StringArgumentType.getString(c,"zone"));c.getSource().sendSuccess(()->Component.literal("Dungeon actualizada y encuentro reiniciado. No se entregan recompensas por reiniciar."),false);return 1;}catch(Exception error){c.getSource().sendFailure(Component.literal(error.getMessage()));return 0;}})))
        .then(Commands.literal("givechest").requires(s->ManagerPermissions.allows(s,"admin",true)).executes(c->{var player=c.getSource().getPlayerOrException();player.getInventory().add(new ItemStack(ManagerBlocks.CRATES.get("loot_common_crate").get().asItem()));return 1;}))
        .then(Commands.literal("pending").requires(s->ManagerPermissions.allows(s,"loot",false)).executes(c->{var player=c.getSource().getPlayerOrException();for(var claim:ManagerRuntime.get().loot().pending(player.getUUID()))player.sendSystemMessage(Component.literal(claim.id()+" · "+claim.trainer()+(claim.review()?" · REVISIÓN":" · PENDIENTE")).withStyle(style->style.withClickEvent(new net.minecraft.network.chat.ClickEvent(net.minecraft.network.chat.ClickEvent.Action.RUN_COMMAND,"/zianmanager claim "+claim.id()))));return 1;}))
        .then(Commands.literal("claim").requires(s->ManagerPermissions.allows(s,"loot",false)).then(Commands.argument("id",StringArgumentType.word()).suggests((c,b)->SharedSuggestionProvider.suggest(ManagerRuntime.get().loot().pending(c.getSource().getPlayerOrException().getUUID()).stream().map(v->v.id().toString()),b)).executes(c->{try{ManagerRuntime.get().loot().deliver(c.getSource().getPlayerOrException(),UUID.fromString(StringArgumentType.getString(c,"id")));return 1;}catch(Exception error){c.getSource().sendFailure(Component.literal(error.getMessage()));return 0;}})))
        .then(Commands.literal("resolvekey").requires(s->ManagerPermissions.allows(s,"admin",true)).then(Commands.argument("player",EntityArgument.player()).then(Commands.argument("id",StringArgumentType.word()).suggests((c,b)->SharedSuggestionProvider.suggest(ManagerRuntime.get().loot().keyReviews(EntityArgument.getPlayer(c,"player").getUUID()).stream().map(v->v.id().toString()),b)).then(Commands.argument("evidence",StringArgumentType.greedyString()).executes(c->{try{var admin=c.getSource().getPlayerOrException();ManagerRuntime.get().loot().resolveKey(UUID.fromString(StringArgumentType.getString(c,"id")),EntityArgument.getPlayer(c,"player").getUUID(),admin.getUUID(),StringArgumentType.getString(c,"evidence"));return 1;}catch(Exception error){c.getSource().sendFailure(Component.literal(error.getMessage()));return 0;}})))))
        .then(Commands.literal("resolve").requires(s->ManagerPermissions.allows(s,"admin",true)).then(Commands.argument("player",EntityArgument.player()).then(Commands.argument("id",StringArgumentType.word()).suggests((c,b)->SharedSuggestionProvider.suggest(ManagerRuntime.get().loot().reviewClaims(EntityArgument.getPlayer(c,"player").getUUID()).stream().map(v->v.id().toString()),b)).then(Commands.argument("part",IntegerArgumentType.integer(1,32)).suggests((c,b)->{try{return SharedSuggestionProvider.suggest(ManagerRuntime.get().loot().reviewParts(EntityArgument.getPlayer(c,"player").getUUID(),UUID.fromString(StringArgumentType.getString(c,"id"))),b);}catch(IllegalArgumentException error){return b.buildFuture();}}).then(Commands.argument("evidence",StringArgumentType.greedyString()).executes(c->{try{var admin=c.getSource().getPlayerOrException();ManagerRuntime.get().loot().resolve(EntityArgument.getPlayer(c,"player").getUUID(),UUID.fromString(StringArgumentType.getString(c,"id")),IntegerArgumentType.getInteger(c,"part")-1,admin.getUUID(),StringArgumentType.getString(c,"evidence"));return 1;}catch(Exception error){c.getSource().sendFailure(Component.literal(error.getMessage()));return 0;}}))))))
    );}
}
